use_frameworks!

platform :ios, '9.0'

target 'TQGatherKit_Example' do
  pod 'TQGatherKit', :path => '../'

  target 'TQGatherKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
